kruskal:
	g++ -lm ok_generator_kruskal.cpp -o ok_generator_kruskal.out && g++ -lm grader_eval_kruskal.cpp -o grader_eval_kruskal.out

tsp:
	g++ -lm ok_generator_tsp.cpp -o ok_generator_tsp.out && g++ -lm grader_eval_tsp.cpp -o grader_eval_tsp.out

clean:
	-rm -f *.out
