kruskal:
	g++ -lm ok_generator.cpp -o ok_generator.out && g++ -lm grader_eval_kruskal.cpp -o grader_eval_kruskal.out

tsp:
	g++ -lm ok_generator.cpp -o ok_generator.out && g++ -lm grader_eval_tsp.cpp -o grader_eval_tsp.out

clean:
	-rm -f *.out
